### ISSUE TITLE
[Suggestion] Use GitHub Actions to publish mods automatically

### ISSUE THREAD

**Issue by Jaffe2718** [TeamMidnightDust/MidnightLib#100]
It's very convenient to use GitHub Actions to automate the release of mods.

## Example
- set repo secrets:
    - `CURSEFORGE_TOKEN`: for Curseforge
    - `GH_RELEASE_TOKEN`: for GitHub releases
    - `MODRINTH_TOKEN`: for Modrinth

- create `Changelog.md` in the project root for changelog
    ```md
    [//]: # (<RELEASE TITLE>)
    
    ## TODO details here
    ```

- in `gradle.properties`
```toml
# other configs
publish_type = release
# or `publish_type = alpha/beta`
```

- in `fabric/build.gradle`
    ```groovy
    // other codes
    
    def publish_changelog = {
        if (rootProject.file('Changelog.md').exists()) {
            println('Found Changelog.md')
            def changelog = ''
            file('Changelog.md').readLines().each { line ->
                changelog += line + '\n'
            }
            println(changelog)
            return changelog
        } else {
            println('Changelog.md not found, skipping changelog upload')
            return ''
        }
    }()
    
    unifiedPublishing {
        project {
            displayName = "MidnightLib $rootProject.version - Fabric $project.minecraft_version"
            releaseType = "$project.release_type"
            changelog = publish_changelog
            gameVersions = []
            gameLoaders = ["fabric","quilt"]
            mainPublication remapJar
            relations {
                depends {
                    curseforge = "fabric-api"
                    modrinth = "fabric-api"
                }
            }
    
            var CURSEFORGE_TOKEN = project.findProperty("CURSEFORGE_TOKEN") ?: System.getenv("CURSEFORGE_TOKEN")
            if (CURSEFORGE_TOKEN != null) {
                curseforge {
                    token = CURSEFORGE_TOKEN
                    id = rootProject.curseforge_id
                    releaseType = rootProject.publish_type
                    gameVersions.addAll "Java 21", project.minecraft_version
                    if (project.supported_versions != "") gameVersions.addAll project.supported_versions
                }
            }
    
            var MODRINTH_TOKEN = project.findProperty("MODRINTH_TOKEN") ?: System.getenv("MODRINTH_TOKEN")
            if (MODRINTH_TOKEN != null) {
                modrinth {
                    token = MODRINTH_TOKEN
                    id = rootProject.modrinth_id
                    version = rootProject.mod_version + "+" + rootProject.minecraft_version + "-" + project.name
                    versionType = rootProject.publish_type
                    gameVersions.addAll project.minecraft_version
                    if (project.supported_versions != "") gameVersions.addAll project.supported_versions
                }
            }
        }
    }
    
    ```

- in `neoforge/build.gradle`
    ```groovy
   // other codes

    def publish_changelog = {
        if (rootProject.file('Changelog.md').exists()) {
            println('Found Changelog.md')
            def changelog = ''
            file('Changelog.md').readLines().each { line ->
                changelog += line + '\n'
            }
            println(changelog)
            return changelog
        } else {
            println('Changelog.md not found, skipping changelog upload')
            return ''
        }
    }()
    
    unifiedPublishing {
        project {
            displayName = "MidnightLib $rootProject.version - NeoForge $project.minecraft_version"
            releaseType = "$project.release_type"
            changelog = publish_changelog
            gameVersions = []
            gameLoaders = ["neoforge"]
            mainPublication remapJar
    
            var CURSEFORGE_TOKEN = project.findProperty("CURSEFORGE_TOKEN") ?: System.getenv("CURSEFORGE_TOKEN")
            if (CURSEFORGE_TOKEN != null) {
                curseforge {
                    token = CURSEFORGE_TOKEN
                    id = rootProject.curseforge_id
                    releaseType = rootProject.publish_type
                    gameVersions.addAll "Java 21", project.minecraft_version
                    if (project.supported_versions != "") gameVersions.addAll project.supported_versions
                }
            }
    
            var MODRINTH_TOKEN = project.findProperty("MODRINTH_TOKEN") ?: System.getenv("MODRINTH_TOKEN")
            if (MODRINTH_TOKEN != null) {
                modrinth {
                    token = MODRINTH_TOKEN
                    id = rootProject.modrinth_id
                    version = rootProject.mod_version + "+" + rootProject.minecraft_version + "-" + project.name
                    versionType = rootProject.publish_type
                    gameVersions.addAll project.minecraft_version
                    if (project.supported_versions != "") gameVersions.addAll project.supported_versions
                }
            }
        }
    }
    ```

- create `.github/workflows/publish.yml`
```yaml
name: Publish

on:
  push:
    branches:
      - architectury-1.21.4

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.actor == github.repository_owner

    steps:
      - name: Checkout base branch
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Read Changelog
        id: read_changelog
        run: |
          if [ -f "Changelog.md" ]; then
            FIRST_LINE=$(head -n 1 Changelog.md)
            RELEASE_TITLE=$(echo "$FIRST_LINE" | awk -F '[()]' '{print $2}')
            echo "release_title=$RELEASE_TITLE"
            echo "release_title=$RELEASE_TITLE" >> $GITHUB_OUTPUT
          else
            echo "Changelog.md not found. Using default values."
            echo "release_title=Release ${{ steps.read_gradle_properties.outputs.tag_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Read Gradle Properties
        id: read_gradle_properties
        run: |   # read ${mod_version}-${minecraft_version} from gradle.properties as tag name
          GRADLE_PROPS=$(cat gradle.properties)
          
          MOD_VERSION=$(echo "$GRADLE_PROPS" | grep 'mod_version = ' | cut -d'=' -f2 | tr -d ' ')
          MINECRAFT_VERSION=$(echo "$GRADLE_PROPS" | grep 'minecraft_version = ' | cut -d'=' -f2 | tr -d ' ')
          TAG_NAME="v${MOD_VERSION}-${MINECRAFT_VERSION}"
          
          PUBLISH_TYPE=$(grep 'publish_type = ' "$GRADLE_PROPERTIES_FILE" | cut -d '=' -f 2 | tr -d ' ')
          
          if [ "$PUBLISH_TYPE" = "release" ]; then
            echo "gh_is_prerelease=false" >> $GITHUB_OUTPUT
          else
            echo "gh_is_prerelease=true" >> $GITHUB_OUTPUT
          fi
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
        with:
          tag_name: ${{ steps.read_gradle_properties.outputs.tag_name }}
          release_name: ${{ steps.read_changelog.outputs.release_title }}
          body_path: Changelog.md
          draft: false
          prerelease: ${{ steps.read_gradle_properties.outputs.gh_is_prerelease }}

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}

      - name: Publish
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: |
          # Modrinth & Curseforge
          ./gradlew :fabric:unifiedPublishing
          ./gradlew :neoforge:unifiedPublishing

          # GitHub Releases
          for jar_file in fabric/build/libs/*.jar; do
            if [ -f "$jar_file" ]; then
              asset_name=$(basename "$jar_file")
              echo "Uploading $jar_file as $asset_name"
              gh release upload ${{ steps.read_gradle_properties.outputs.tag_name }} "$jar_file" --clobber
            fi
          done
          for jar_file in neoforge/build/libs/*.jar; do
            if [ -f "$jar_file" ]; then
              asset_name=$(basename "$jar_file")
              echo "Uploading $jar_file as $asset_name"
              gh release upload ${{ steps.read_gradle_properties.outputs.tag_name }} "$jar_file" --clobber
            fi
          done

          # TODO: maven publish ?
```

## Note

In normal development and maintenance of mod's code, it should be pushed to a non-default branch, such as the dev branch, after committing. When you need to publish, you only need to initiate a pull request and successfully merge to the default branch. These GitHub Actions are for reference only and need to be modified according to the actual situation.
